<?php

return [
    'roles' => [
        'admin' => [
            'name' => 'Admin',
            'display_name' => 'Quản trị viên',
            'description' => 'Full system access.',
        ],
        'theater_manager' => [
            'name' => 'Theater Manager',
            'display_name' => 'Quản lý rạp',
            'description' => 'Manages theater operations for assigned theaters.',
        ],
        'ticket_seller' => [
            'name' => 'Ticket Seller',
            'display_name' => 'Nhân viên bán vé',
            'description' => 'Creates box office bookings and payments.',
        ],
        'ticket_checker' => [
            'name' => 'Ticket Checker',
            'display_name' => 'Nhân viên soát vé',
            'description' => 'Verifies tickets and marks tickets as used.',
        ],
        'concession_staff' => [
            'name' => 'Concession Staff',
            'display_name' => 'Nhân viên quầy bắp nước',
            'description' => 'Handles concession products and combo fulfillment.',
        ],
        'customer' => [
            'name' => 'Customer',
            'display_name' => 'Khách hàng',
            'description' => 'Registered customer account.',
        ],
    ],

    'legacy_role_map' => [
        'manager' => 'theater_manager',
        'staff' => 'ticket_seller',
        'user' => 'customer',
    ],

    'permissions' => [
        'users' => [
            'users.view' => 'Xem người dùng',
            'users.create' => 'Tạo người dùng',
            'users.update' => 'Cập nhật người dùng',
            'users.delete' => 'Xóa người dùng',
            'users.manage_roles' => 'Quản lý vai trò người dùng',
            'users.manage_status' => 'Quản lý trạng thái người dùng',
            'users.manage_loyalty' => 'Quản lý điểm thành viên',
            'roles.view' => 'Xem vai trò',
            'roles.create' => 'Tạo vai trò',
            'roles.update' => 'Cập nhật vai trò',
            'roles.delete' => 'Xóa vai trò',
            'permissions.assign' => 'Gán quyền',
        ],
        'movies' => [
            'movies.view' => 'Xem phim',
            'movies.create' => 'Tạo phim',
            'movies.update' => 'Cập nhật phim',
            'movies.delete' => 'Xóa phim',
            'movies.publish' => 'Công bố phim',
            'movie_categories.manage' => 'Quản lý thể loại phim',
            'formats.manage' => 'Quản lý định dạng phim',
            'subtitles.manage' => 'Quản lý phụ đề',
            'sounds.manage' => 'Quản lý âm thanh',
        ],
        'theaters' => [
            'branches.view' => 'Xem chi nhánh',
            'branches.create' => 'Tạo chi nhánh',
            'branches.update' => 'Cập nhật chi nhánh',
            'branches.delete' => 'Xóa chi nhánh',
            'theaters.view' => 'Xem rạp chiếu',
            'theaters.create' => 'Tạo rạp chiếu',
            'theaters.update' => 'Cập nhật rạp chiếu',
            'theaters.delete' => 'Xóa rạp chiếu',
            'screens.view' => 'Xem phòng chiếu',
            'screens.create' => 'Tạo phòng chiếu',
            'screens.update' => 'Cập nhật phòng chiếu',
            'screens.delete' => 'Xóa phòng chiếu',
            'screens.manage_seats' => 'Quản lý ghế phòng chiếu',
            'seat_layouts.view' => 'Xem sơ đồ ghế',
            'seat_layouts.create' => 'Tạo sơ đồ ghế',
            'seat_layouts.update' => 'Cập nhật sơ đồ ghế',
            'seat_layouts.delete' => 'Xóa sơ đồ ghế',
        ],
        'showtimes' => [
            'showtimes.view' => 'Xem suất chiếu',
            'showtimes.create' => 'Tạo suất chiếu',
            'showtimes.update' => 'Cập nhật suất chiếu',
            'showtimes.delete' => 'Xóa suất chiếu',
            'showtimes.bulk_create' => 'Tạo suất chiếu hàng loạt',
        ],
        'booking' => [
            'seats.view_status' => 'Xem trạng thái ghế',
            'booking.hold_seats' => 'Giữ ghế',
            'booking.release_seats' => 'Hủy giữ ghế',
            'booking.create_order' => 'Tạo đơn đặt vé',
            'booking.guest_checkout' => 'Thanh toán khách vãng lai',
            'customers.lookup' => 'Tra cứu khách hàng tại quầy',
            'customers.create_walk_in' => 'Tạo khách vãng lai tại quầy',
        ],
        'orders' => [
            'orders.view_all' => 'Xem tất cả đơn hàng',
            'orders.view_theater' => 'Xem đơn hàng theo rạp',
            'orders.view_own' => 'Xem đơn hàng của chính mình',
            'orders.create' => 'Tạo đơn hàng',
            'orders.cancel' => 'Hủy đơn hàng',
            'orders.refund' => 'Hoàn tiền đơn hàng',
            'orders.export' => 'Xuất đơn hàng',
            'tickets.view' => 'Xem vé',
            'tickets.issue' => 'Phát hành vé',
            'tickets.verify' => 'Xác thực vé',
            'tickets.mark_used' => 'Đánh dấu vé đã sử dụng',
            'tickets.cancel' => 'Hủy vé',
        ],
        'payments' => [
            'payments.process' => 'Xử lý thanh toán',
            'payments.process_cash' => 'Xác nhận thanh toán tiền mặt',
            'payments.view' => 'Xem thanh toán',
            'payments.verify' => 'Xác minh thanh toán',
            'payments.refund' => 'Hoàn tiền thanh toán',
            'payments.webhook_manage' => 'Quản lý webhook thanh toán',
        ],
        'concessions' => [
            'products.view' => 'Xem sản phẩm',
            'products.create' => 'Tạo sản phẩm',
            'products.update' => 'Cập nhật sản phẩm',
            'products.delete' => 'Xóa sản phẩm',
            'products.toggle_status' => 'Bật/tắt trạng thái sản phẩm',
            'combos.view' => 'Xem combo',
            'combos.create' => 'Tạo combo',
            'combos.update' => 'Cập nhật combo',
            'combos.delete' => 'Xóa combo',
            'combos.toggle_status' => 'Bật/tắt trạng thái combo',
            'concessions.fulfill' => 'Xác nhận giao bắp nước',
        ],
        'promotions' => [
            'promotions.view' => 'Xem khuyến mãi',
            'promotions.create' => 'Tạo khuyến mãi',
            'promotions.update' => 'Cập nhật khuyến mãi',
            'promotions.delete' => 'Xóa khuyến mãi',
            'promotions.apply' => 'Áp dụng khuyến mãi',
            'promotions.reset_usage' => 'Đặt lại lượt dùng khuyến mãi',
            'vouchers.claim' => 'Nhận voucher',
            'loyalty.view' => 'Xem điểm thành viên',
            'loyalty.use_points' => 'Sử dụng điểm thành viên',
            'loyalty.adjust_points' => 'Điều chỉnh điểm thành viên',
        ],
        'content' => [
            'posts.view' => 'Xem bài viết',
            'posts.create' => 'Tạo bài viết',
            'posts.update' => 'Cập nhật bài viết',
            'posts.delete' => 'Xóa bài viết',
            'posts.publish' => 'Công bố bài viết',
            'banners.view' => 'Xem banner',
            'banners.create' => 'Tạo banner',
            'banners.update' => 'Cập nhật banner',
            'banners.delete' => 'Xóa banner',
            'banners.toggle_status' => 'Bật/tắt trạng thái banner',
        ],
        'system' => [
            'dashboard.view' => 'Xem dashboard',
            'reports.view' => 'Xem báo cáo',
            'reports.export' => 'Xuất báo cáo',
            'analytics.view' => 'Xem phân tích',
            'pricing.quote_pos' => 'Tính giá đơn hàng tại quầy',
            'pricing.view' => 'Xem bảng giá',
            'pricing.update' => 'Cập nhật bảng giá',
            'audit_logs.view' => 'Xem nhật ký hoạt động',
            'settings.manage' => 'Quản lý cài đặt hệ thống',
        ],
    ],

    'permission_aliases' => [
        'view_users' => 'users.view',
        'create_users' => 'users.create',
        'edit_users' => 'users.update',
        'delete_users' => 'users.delete',
        'manage_user_roles' => 'users.manage_roles',
        'view_movies' => 'movies.view',
        'create_movies' => 'movies.create',
        'edit_movies' => 'movies.update',
        'delete_movies' => 'movies.delete',
        'manage_movie_categories' => 'movie_categories.manage',
        'view_theaters' => 'theaters.view',
        'create_theaters' => 'theaters.create',
        'edit_theaters' => 'theaters.update',
        'delete_theaters' => 'theaters.delete',
        'view_screens' => 'screens.view',
        'create_screens' => 'screens.create',
        'edit_screens' => 'screens.update',
        'delete_screens' => 'screens.delete',
        'manage_seat_layouts' => 'screens.manage_seats',
        'view_showtimes' => 'showtimes.view',
        'create_showtimes' => 'showtimes.create',
        'edit_showtimes' => 'showtimes.update',
        'delete_showtimes' => 'showtimes.delete',
        'view_all_orders' => 'orders.view_all',
        'view_own_orders' => 'orders.view_own',
        'create_orders' => 'orders.create',
        'cancel_orders' => 'orders.cancel',
        'refund_orders' => 'orders.refund',
        'book_tickets' => 'booking.create_order',
        'hold_seats' => 'booking.hold_seats',
        'release_seats' => 'booking.release_seats',
        'process_payments' => 'payments.process',
        'view_payment_details' => 'payments.view',
        'verify_payments' => 'payments.verify',
        'view_promotions' => 'promotions.view',
        'create_promotions' => 'promotions.create',
        'edit_promotions' => 'promotions.update',
        'delete_promotions' => 'promotions.delete',
        'apply_promotions' => 'promotions.apply',
        'view_dashboard' => 'dashboard.view',
        'view_reports' => 'reports.view',
        'export_reports' => 'reports.export',
        'manage_settings' => 'settings.manage',
        'view_audit_logs' => 'audit_logs.view',
        'manage_roles_permissions' => 'permissions.assign',
    ],

    'role_permissions' => [
        'admin' => ['*'],
        'theater_manager' => [
            'dashboard.view',
            'reports.view',
            'reports.export',
            'analytics.view',
            'movies.view',
            'branches.view',
            'theaters.view',
            'theaters.update',
            'screens.view',
            'screens.create',
            'screens.update',
            'screens.manage_seats',
            'seat_layouts.view',
            'seat_layouts.create',
            'seat_layouts.update',
            'showtimes.view',
            'showtimes.create',
            'showtimes.update',
            'showtimes.delete',
            'showtimes.bulk_create',
            'orders.view_theater',
            'orders.cancel',
            'orders.refund',
            'tickets.view',
            'payments.view',
            'payments.verify',
            'products.view',
            'combos.view',
            'concessions.fulfill',
            'users.view',
            'users.create',
            'users.update',
        ],
        'ticket_seller' => [
            'movies.view',
            'theaters.view',
            'screens.view',
            'showtimes.view',
            'seats.view_status',
            'booking.hold_seats',
            'booking.release_seats',
            'booking.create_order',
            'customers.lookup',
            'customers.create_walk_in',
            'orders.create',
            'orders.view_theater',
            'orders.cancel',
            'tickets.issue',
            'payments.process',
            'payments.process_cash',
            'pricing.quote_pos',
            'payments.view',
            'promotions.apply',
            'products.view',
            'combos.view',
        ],
        'ticket_checker' => [
            'movies.view',
            'showtimes.view',
            'orders.view_theater',
            'tickets.view',
            'tickets.verify',
            'tickets.mark_used',
        ],
        'concession_staff' => [
            'products.view',
            'combos.view',
            'orders.view_theater',
            'orders.create',
            'payments.process',
            'concessions.fulfill',
        ],
        'customer' => [
            'movies.view',
            'theaters.view',
            'showtimes.view',
            'seats.view_status',
            'booking.hold_seats',
            'booking.release_seats',
            'booking.create_order',
            'orders.view_own',
            'orders.create',
            'orders.cancel',
            'payments.process',
            'promotions.apply',
            'vouchers.claim',
            'loyalty.view',
            'loyalty.use_points',
        ],
    ],
];
